name: flutter_supabase_template
description: "Flutter Supabase Template."
publish_to: 'none'

version: 1.0.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  powersync: ^1.16.1
  supabase_flutter: ^2.10.1
  path_provider: ^2.1.1
  path: ^1.8.3
  logging: ^1.2.0
  sqlite_async: ^0.12.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true